x-node_template: &node_template
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - .:/App
  networks:
    - shard_network
  restart: always

services:
  node1:
    <<: *node_template
    environment:
      - SHARD_NODE_TYPE=Leader
    ports:
      - "5000:6379"

  node2:
    <<: *node_template
    environment:
      - SHARD_NODE_TYPE=Follower
    ports:
      - "5001:6379"

  node3:
    <<: *node_template
    environment:
      - SHARD_NODE_TYPE=Follower
    ports:
      - "5002:6379"

  node4:
    <<: *node_template
    environment:
      - SHARD_NODE_TYPE=Follower
    ports:
      - "5003:6379"

networks:
  shard_network:
    driver: bridge